#!/bin/bash

# Build Recipe for NVIDIA V100 machine; adjust according to your GPU
# microarchitecture

# TODO:  Set your desired install point
#
#export INSTALL_DIR=$HOME/kokkos_install_cuda

cmake \
-DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=OFF \
-DKokkos_ENABLE_TESTS=OFF \
-DKokkos_ENABLE_CUDA=ON \
-DKokkos_ARCH_VOLTA70=ON \
-DKokkos_ENABLE_SERIAL=ON \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_CXX_STANDARD=17 \
-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
-DCMAKE_BUILD_TYPE=Release ..

